language: ruby
rvm:
  - 2.3.0
before_script:
  - bundle install
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake db:seed
  - bundle exec rails s -d

script: 
  - RAILS_ENV=development bin/delayed_job start forstarting background jobs
  - bundle exec rake recurring:init
  - bundle exec rspec spec
  